image: docker:latest
services:
  - docker:dind

stages:
  - build
     
docker-build:
  stage: build
  script:
  - docker build -t dmoutinho/$CI_COMMIT_REF_NAME .
  - docker login -u dmoutinho -p $DOCKER_PASS
  - docker push dmoutinho/$CI_COMMIT_REF_NAME
