image: docker:latest
services:
  - docker:dind

stages:
  - build
  - test
  
npm-test:
  image: dmoutinho/kubectl-gcloud
  stage: test
  script:
  - npm install
  - npm test

docker-build:
  stage: build
  script:
  - docker build -t dmoutinho/insured-app .
  - docker login -u dmoutinho -p $DOCKER_PASS
  - docker push dmoutinho/insured-app
