image: docker:latest
services:
  - docker:dind

variables:
  IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME

stages:
  - build
     
docker-build:
  stage: build
  script:
  - docker build -t $IMAGE_TAG .
  - docker login -u dmoutinho -p $DOCKER_PASS
  - docker tag $IMAGE_TAG dmoutinho/$IMAGE_TAG
  - docker push dmoutinho/$IMAGE_TAG